In [2]:
def process_string(input_string):
    # 1. 각 라인 별로 맨 마지막 숫자 뒤에 위치한 띄어쓰기를 지움
    cleaned_lines = []
    for line in input_string.split('\n'):
        cleaned_line = line.rstrip(' ')
        cleaned_lines.append(cleaned_line)

    # 2. '개행 문자'를 기준으로 하여 인풋을 나누고, 각 인풋을 임의의 리스트에 추가
    lines_list = cleaned_lines

    # 3. 인풋을 띄어쓰기(' ')를 기준으로 하여 임의의 리스트에 추가하고, 이 리스트를 임의의 리스트에 추가
    # 이때, 인풋은 float 형식으로 캐스팅
    float_list = []
    for line in lines_list:
        float_line = [float(num) for num in line.split()]
        float_list.append(float_line)

    # 4. 2의 리스트와 3의 리스트를 반환
    return lines_list, float_list

In [10]:
input_string = """-1.253320    89.754211    0.253828    0.271554    -0.067930    1.044649    0.004671    -2.702317    0.099076    0.060130    1.649928    0.097193    -1.134144    -0.654619    -0.068749    -0.592515    -1.744542    -0.073797    4.619843    1.398346    -0.551397    0.231909    2.703840    -2.213668    -0.062974    -1.342286    -2.686267    0.582811    -0.443560    -0.297010    28.697569    36.280907    -42.816929    -22.867786    -4.684815    22.867792    -0.000000    0.000000    -0.000000    -0.030086    17.999952    -0.013040    -0.028610    0.000004    -0.000001    -0.028613    0.000000    0.000000    -0.028612    0.000000    -0.011169    -0.028612    0.000000    0.000000    -0.028612    0.000000    -0.000001    -0.028613    -0.000000    0.007448    -0.028611    0.000000    -0.000001    -0.028612    0.000000    -0.000001    -0.030085    -17.999950    0.005596    -0.028612    0.000001    0.000000    -0.028612    -0.000001    -0.000000    -4.772783    1.999592    0.825455    -0.117561    3.553278    2.707637    0.017834    -0.575927    1.773762    -0.139505    -0.209332    -0.833632    -28.697580    36.280907    42.816933    22.867792    -4.684811    -22.867790    -0.000000    0.000000    -0.000000    0.030084    17.999950    0.013042    0.028612    0.000004    0.000000    0.028612    -0.000001    -0.000001    0.028612    0.000000    0.011169    0.028613    -0.000001    -0.000001    0.028611    0.000001    0.000001    0.028611    0.000001    -0.007446    0.028612    -0.000001    -0.000001    0.028611    0.000001    0.000001    0.030085    -17.999954    -0.005596    0.028612    -0.000001    0.000000    0.028611    -0.000004    0.000002    2.131844    2.218729    1.965265    -0.000000    4.369233    -0.000000    -1.368979    -3.782383    -1.345939    -0.000000    -1.809301    -0.000000    -2.324459    1.002725    -2.611902    -0.000000    6.871911    -0.000000    -0.729075    -5.179983    -2.688388    0.000001    -1.987515    0.000002    
-1.327959    89.904915    0.724199    0.270495    -0.634992    1.468915    0.002558    -4.080041    0.035957    -0.020909    3.852391    0.037190    -1.403814    -0.370355    -0.197857    -0.690762    -2.080945    -0.213701    6.573526    0.987751    -0.591955    -2.005956    3.511819    -2.878868    -0.143424    -2.529750    -3.245975    -1.593586    -0.607432    0.342367    28.684042    36.291019    -42.838661    -22.867785    -4.684802    22.867785    -0.000000    0.000000    -0.000000    -0.060019    17.999950    -0.026101    -0.057082    -0.000007    0.000001    -0.057081    0.000007    -0.000002    -0.057082    -0.000000    -0.022323    -0.057081    0.000000    -0.000000    -0.057082    -0.000000    0.000000    -0.057081    0.000000    0.014883    -0.057081    -0.000000    -0.000001    -0.057081    0.000000    -0.000001    -0.060019    -17.999950    0.011218    -0.057082    0.000008    0.000002    -0.057081    -0.000004    -0.000001    -6.673431    1.537056    0.599108    2.243140    4.661649    3.455371    0.027494    -1.056882    1.490286    1.929382    -0.312841    -2.717893    -28.684046    36.291019    42.838665    22.867792    -4.684815    -22.867786    -0.000000    0.000000    -0.000000    0.060019    17.999950    0.026100    0.057082    -0.000004    -0.000001    0.057081    0.000004    0.000001    0.057081    0.000000    0.022324    0.057081    -0.000001    -0.000001    0.057081    -0.000000    -0.000000    0.057082    -0.000001    -0.014884    0.057081    0.000000    0.000000    0.057081    0.000000    -0.000000    0.060019    -17.999950    -0.011218    0.057081    0.000001    -0.000000    0.057081    0.000001    -0.000000    2.602724    2.488044    3.201402    -0.000000    5.880136    -0.000000    -3.286563    -5.459153    -3.382217    -0.000000    -2.374916    0.000000    -2.467018    0.617754    -3.759274    0.000000    10.177664    0.000000    0.877259    -7.854818    -2.298363    0.000000    -2.595023    0.000000    
-1.371685    89.747772    1.149350    0.226914    -1.292518    1.884882    -0.006878    -5.598317    -0.070508    -0.073739    6.816130    -0.060923    -1.473313    -0.349851    -0.366863    -0.527843    -2.890834    -0.383934    9.500789    -0.148224    -0.618693    -5.222422    4.482032    -3.442607    -0.260781    -4.505048    -3.316375    -4.501883    -0.935825    1.635679    28.659761    36.309238    -42.877754    -22.867786    -4.684810    22.867783    -0.000000    0.000000    -0.000000    -0.113632    17.999926    -0.049637    -0.108070    0.000002    -0.000000    -0.108070    0.000002    0.000000    -0.108070    -0.000000    -0.042376    -0.108070    0.000000    -0.000000    -0.108070    -0.000000    0.000000    -0.108070    0.000000    0.028251    -0.108070    -0.000000    -0.000000    -0.108070    0.000000    -0.000000    -0.113632    -17.999922    0.021386    -0.108070    0.000000    0.000000    -0.108070    -0.000002    0.000000    -9.466858    0.166594    0.248384    5.645549    5.809784    4.410089    0.028655    -1.901599    0.863460    4.912674    -0.687233    -5.703910    -28.659761    36.309238    42.877754    22.867785    -4.684804    -22.867785    -0.000000    0.000000    -0.000000    0.113632    17.999929    0.049638    0.108070    0.000000    -0.000000    0.108070    -0.000003    -0.000000    0.108070    0.000001    0.042376    0.108070    0.000000    0.000000    0.108070    -0.000001    -0.000000    0.108070    0.000000    -0.028250    0.108070    0.000000    0.000000    0.108070    -0.000000    -0.000000    0.113631    -17.999924    -0.021387    0.108070    -0.000001    0.000000    0.108070    -0.000003    0.000000    3.106492    2.665897    5.334058    -0.000000    7.595031    -0.000000    -6.039884    -7.080389    -6.465300    0.000000    -2.911741    -0.000000    -2.714119    0.033306    -5.980019    -0.000001    13.850174    -0.000001    3.437849    -10.903557    -0.907659    -0.000000    -3.057506    -0.000000    """
lines_list, float_list = process_string(input_string)

# print("Lines List:", lines_list)
print("Float List:", float_list)

Float List: [[-1.25332, 89.754211, 0.253828, 0.271554, -0.06793, 1.044649, 0.004671, -2.702317, 0.099076, 0.06013, 1.649928, 0.097193, -1.134144, -0.654619, -0.068749, -0.592515, -1.744542, -0.073797, 4.619843, 1.398346, -0.551397, 0.231909, 2.70384, -2.213668, -0.062974, -1.342286, -2.686267, 0.582811, -0.44356, -0.29701, 28.697569, 36.280907, -42.816929, -22.867786, -4.684815, 22.867792, -0.0, 0.0, -0.0, -0.030086, 17.999952, -0.01304, -0.02861, 4e-06, -1e-06, -0.028613, 0.0, 0.0, -0.028612, 0.0, -0.011169, -0.028612, 0.0, 0.0, -0.028612, 0.0, -1e-06, -0.028613, -0.0, 0.007448, -0.028611, 0.0, -1e-06, -0.028612, 0.0, -1e-06, -0.030085, -17.99995, 0.005596, -0.028612, 1e-06, 0.0, -0.028612, -1e-06, -0.0, -4.772783, 1.999592, 0.825455, -0.117561, 3.553278, 2.707637, 0.017834, -0.575927, 1.773762, -0.139505, -0.209332, -0.833632, -28.69758, 36.280907, 42.816933, 22.867792, -4.684811, -22.86779, -0.0, 0.0, -0.0, 0.030084, 17.99995, 0.013042, 0.028612, 4e-06, 0.0, 0.028612, -1e-06, -1e-06

In [23]:
print(len(float_list), len(float_list[0]), len(float_list[1]), len(float_list[2]))
for i in float_list[0]:
    print(type(i))

3 156 156 156
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'fl

In [25]:
import re

given_string = """
ROOT Hips
{
    OFFSET 0.000000 0.000000 0.000000
    CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
    JOINT Spine
    {
        OFFSET 0.000000 8.456228 0.000000
        CHANNELS 3 Zrotation Xrotation Yrotation
        JOINT Spine1
        {
            OFFSET -0.000000 20.815973 -0.000000
            CHANNELS 3 Zrotation Xrotation Yrotation
            JOINT Neck
            {
                OFFSET -0.000000 21.138641 -0.000000
                CHANNELS 3 Zrotation Xrotation Yrotation
                JOINT Head
                {
                    OFFSET 0.000000 13.829141 1.905770
                    CHANNELS 3 Zrotation Xrotation Yrotation
                    End Site
                    {
                        OFFSET 0.000000 19.057678 0.000000
                    }
                }
            }
            JOINT LeftShoulder
            {
                OFFSET 3.811190 13.242801 -0.071952
                CHANNELS 3 Zrotation Xrotation Yrotation
                JOINT LeftArm
                {
                    OFFSET 18.187696 0.000000 -0.000000
                    CHANNELS 3 Zrotation Xrotation Yrotation
                    JOINT LeftForeArm
                    {
                        OFFSET 23.594999 -0.000003 0.000000
                        CHANNELS 3 Zrotation Xrotation Yrotation
                        JOINT LeftHand
                        {
                            OFFSET 24.530102 0.000004 0.000000
                            CHANNELS 3 Zrotation Xrotation Yrotation
                            JOINT LeftHandThumb1
                            {
                                OFFSET 1.991529 -2.263100 3.168340
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT LeftHandThumb2
                                {
                                    OFFSET 3.007898 0.000004 -0.000002
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT LeftHandThumb3
                                    {
                                        OFFSET 2.570877 -0.000002 0.000003
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET 2.449750 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT LeftHandIndex1
                            {
                                OFFSET 8.147160 0.000003 3.168340
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT LeftHandIndex2
                                {
                                    OFFSET 4.526201 -0.000003 0.000001
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT LeftHandIndex3
                                    {
                                        OFFSET 2.263098 -0.000003 0.000001
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET 2.156472 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT LeftHandMiddle1
                            {
                                OFFSET 8.147158 0.000001 1.050080
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT LeftHandMiddle2
                                {
                                    OFFSET 4.978823 -0.000004 -0.000000
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT LeftHandMiddle3
                                    {
                                        OFFSET 2.715720 0.000004 -0.000000
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET 2.587766 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT LeftHandRing1
                            {
                                OFFSET 7.694540 0.000002 -1.050080
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT LeftHandRing2
                                {
                                    OFFSET 4.526197 -0.000005 0.000000
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT LeftHandRing3
                                    {
                                        OFFSET 2.263100 0.000001 -0.000000
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET 2.156472 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT LeftHandPinky1
                            {
                                OFFSET 7.241915 -0.000006 -3.168340
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT LeftHandPinky2
                                {
                                    OFFSET 3.620959 0.000005 0.000002
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT LeftHandPinky3
                                    {
                                        OFFSET 1.810482 -0.000004 -0.000001
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET 1.725177 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            JOINT RightShoulder
            {
                OFFSET -3.811190 13.242799 -0.071952
                CHANNELS 3 Zrotation Xrotation Yrotation
                JOINT RightArm
                {
                    OFFSET -18.187696 -0.000006 0.000000
                    CHANNELS 3 Zrotation Xrotation Yrotation
                    JOINT RightForeArm
                    {
                        OFFSET -23.595001 0.000002 0.000000
                        CHANNELS 3 Zrotation Xrotation Yrotation
                        JOINT RightHand
                        {
                            OFFSET -24.530102 -0.000002 0.000000
                            CHANNELS 3 Zrotation Xrotation Yrotation
                            JOINT RightHandThumb1
                            {
                                OFFSET -1.991528 -2.263100 3.168341
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT RightHandThumb2
                                {
                                    OFFSET -3.007902 0.000000 -0.000003
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT RightHandThumb3
                                    {
                                        OFFSET -2.570879 -0.000001 0.000000
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET -2.449750 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT RightHandIndex1
                            {
                                OFFSET -8.147161 -0.000001 3.168341
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT RightHandIndex2
                                {
                                    OFFSET -4.526201 -0.000001 -0.000000
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT RightHandIndex3
                                    {
                                        OFFSET -2.263099 -0.000004 0.000002
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET -2.156472 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT RightHandMiddle1
                            {
                                OFFSET -8.147161 -0.000000 1.050080
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT RightHandMiddle2
                                {
                                    OFFSET -4.978818 -0.000002 0.000000
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT RightHandMiddle3
                                    {
                                        OFFSET -2.715719 0.000005 -0.000000
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET -2.587766 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT RightHandRing1
                            {
                                OFFSET -7.694539 -0.000001 -1.050080
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT RightHandRing2
                                {
                                    OFFSET -4.526198 -0.000005 0.000001
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT RightHandRing3
                                    {
                                        OFFSET -2.263102 -0.000005 0.000000
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET -2.156472 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                            JOINT RightHandPinky1
                            {
                                OFFSET -7.241919 -0.000004 -3.168340
                                CHANNELS 3 Zrotation Xrotation Yrotation
                                JOINT RightHandPinky2
                                {
                                    OFFSET -3.620958 -0.000005 -0.000001
                                    CHANNELS 3 Zrotation Xrotation Yrotation
                                    JOINT RightHandPinky3
                                    {
                                        OFFSET -1.810482 -0.000004 -0.000001
                                        CHANNELS 3 Zrotation Xrotation Yrotation
                                        End Site
                                        {
                                            OFFSET -1.725177 0.000000 0.000000
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    JOINT LeftUpLeg
    {
        OFFSET 9.528839 -0.000001 -0.000000
        CHANNELS 3 Zrotation Xrotation Yrotation
        JOINT LeftLeg
        {
            OFFSET -0.000001 -36.574291 0.000000
            CHANNELS 3 Zrotation Xrotation Yrotation
            JOINT LeftFoot
            {
                OFFSET -0.000000 -40.646587 -0.000000
                CHANNELS 3 Zrotation Xrotation Yrotation
                JOINT LeftToeBase
                {
                    OFFSET -0.000000 -6.193748 14.293295
                    CHANNELS 3 Zrotation Xrotation Yrotation
                    End Site
                    {
                        OFFSET 0.000000 0.000000 3.811536
                    }
                }
            }
        }
    }
    JOINT RightUpLeg
    {
        OFFSET -9.528839 0.000001 0.000000
        CHANNELS 3 Zrotation Xrotation Yrotation
        JOINT RightLeg
        {
            OFFSET 0.000000 -36.574299 0.000000
            CHANNELS 3 Zrotation Xrotation Yrotation
            JOINT RightFoot
            {
                OFFSET 0.000001 -40.646587 0.000000
                CHANNELS 3 Zrotation Xrotation Yrotation
                JOINT RightToeBase
                {
                    OFFSET 0.000001 -6.193748 14.293295
                    CHANNELS 3 Zrotation Xrotation Yrotation
                    End Site
                    {
                        OFFSET 0.000000 0.000000 3.811536
                    }
                }
            }
        }
    }
}"""
joint_lines = [line.strip() for line in given_string.split('\n') if "JOINT" in line]
jnt_words = [line.split()[1] for line in joint_lines]
jnt_words.insert(0, 'Hips')
jnt_words.insert(0, 'Hips_pos')

print(jnt_words, len(jnt_words))

['Hips_pos', 'Hips', 'Spine', 'Spine1', 'Neck', 'Head', 'LeftShoulder', 'LeftArm', 'LeftForeArm', 'LeftHand', 'LeftHandThumb1', 'LeftHandThumb2', 'LeftHandThumb3', 'LeftHandIndex1', 'LeftHandIndex2', 'LeftHandIndex3', 'LeftHandMiddle1', 'LeftHandMiddle2', 'LeftHandMiddle3', 'LeftHandRing1', 'LeftHandRing2', 'LeftHandRing3', 'LeftHandPinky1', 'LeftHandPinky2', 'LeftHandPinky3', 'RightShoulder', 'RightArm', 'RightForeArm', 'RightHand', 'RightHandThumb1', 'RightHandThumb2', 'RightHandThumb3', 'RightHandIndex1', 'RightHandIndex2', 'RightHandIndex3', 'RightHandMiddle1', 'RightHandMiddle2', 'RightHandMiddle3', 'RightHandRing1', 'RightHandRing2', 'RightHandRing3', 'RightHandPinky1', 'RightHandPinky2', 'RightHandPinky3', 'LeftUpLeg', 'LeftLeg', 'LeftFoot', 'LeftToeBase', 'RightUpLeg', 'RightLeg', 'RightFoot', 'RightToeBase'] 52


In [26]:
# Dataframe 생성

In [27]:
import pandas as pd
import numpy as np

In [28]:
df_list = []
for i in float_list:
    df_list.append(pd.DataFrame(np.array(i).reshape(52, 3),
                               index = jnt_words,
                               columns = ['Z', 'X', 'Y']))

# df_list_b = []
# for i in float_list_b:
#     df_list_b.append(pd.DataFrame(np.array(i).reshape(53, 3),
#                                index = jnt_words,
#                                columns = ['Z', 'X', 'Y']))

In [29]:
df_list

[                          Z          X          Y
 Hips_pos          -1.253320  89.754211   0.253828
 Hips               0.271554  -0.067930   1.044649
 Spine              0.004671  -2.702317   0.099076
 Spine1             0.060130   1.649928   0.097193
 Neck              -1.134144  -0.654619  -0.068749
 Head              -0.592515  -1.744542  -0.073797
 LeftShoulder       4.619843   1.398346  -0.551397
 LeftArm            0.231909   2.703840  -2.213668
 LeftForeArm       -0.062974  -1.342286  -2.686267
 LeftHand           0.582811  -0.443560  -0.297010
 LeftHandThumb1    28.697569  36.280907 -42.816929
 LeftHandThumb2   -22.867786  -4.684815  22.867792
 LeftHandThumb3    -0.000000   0.000000  -0.000000
 LeftHandIndex1    -0.030086  17.999952  -0.013040
 LeftHandIndex2    -0.028610   0.000004  -0.000001
 LeftHandIndex3    -0.028613   0.000000   0.000000
 LeftHandMiddle1   -0.028612   0.000000  -0.011169
 LeftHandMiddle2   -0.028612   0.000000   0.000000
 LeftHandMiddle3   -0.028612   

In [30]:
for i in df_list:
    print(i.count())

Z    52
X    52
Y    52
dtype: int64
Z    52
X    52
Y    52
dtype: int64
Z    52
X    52
Y    52
dtype: int64


# 필요 없는 관절 제거
- 제거 후 21개 (Root Position + 20개 관절의 Rotation)

In [34]:
# List of strings to remove
strings_to_remove = ['Spine1',
                    'LeftHandThumb1','LeftHandThumb2','LeftHandThumb3',
                    'LeftHandIndex1','LeftHandIndex2','LeftHandIndex3',
                    'LeftHandMiddle1','LeftHandMiddle2','LeftHandMiddle3',
                    'LeftHandRing1','LeftHandRing2','LeftHandRing3',
                    'LeftHandPinky1','LeftHandPinky2','LeftHandPinky3',
                    'RightHandThumb1','RightHandThumb2','RightHandThumb3',
                    'RightHandIndex1','RightHandIndex2','RightHandIndex3',
                    'RightHandMiddle1','RightHandMiddle2','RightHandMiddle3',
                    'RightHandRing1','RightHandRing2','RightHandRing3',
                    'RightHandPinky1','RightHandPinky2','RightHandPinky3']

# Drop the rows with index labels matching the strings in the list
df_buf = []
for i in df_list:
    df_buf.append(i.drop(strings_to_remove))

# df_buf_b = []
# for i in df_list_b:
#     df_buf_b.append(i.drop(strings_to_remove))
    
for j in df_buf:
    print(j.count())

Z    21
X    21
Y    21
dtype: int64
Z    21
X    21
Y    21
dtype: int64
Z    21
X    21
Y    21
dtype: int64


In [35]:
df_buf[1]

Z          X         Y
Hips_pos      -1.327959  89.904915  0.724199
Hips           0.270495  -0.634992  1.468915
Spine          0.002558  -4.080041  0.035957
Neck          -1.403814  -0.370355 -0.197857
Head          -0.690762  -2.080945 -0.213701
LeftShoulder   6.573526   0.987751 -0.591955
LeftArm       -2.005956   3.511819 -2.878868
LeftForeArm   -0.143424  -2.529750 -3.245975
LeftHand      -1.593586  -0.607432  0.342367
RightShoulder -6.673431   1.537056  0.599108
RightArm       2.243140   4.661649  3.455371
RightForeArm   0.027494  -1.056882  1.490286
RightHand      1.929382  -0.312841 -2.717893
LeftUpLeg      2.602724   2.488044  3.201402
LeftLeg       -0.000000   5.880136 -0.000000
LeftFoot      -3.286563  -5.459153 -3.382217
LeftToeBase   -0.000000  -2.374916  0.000000
RightUpLeg    -2.467018   0.617754 -3.759274
RightLeg       0.000000  10.177664  0.000000
RightFoot      0.877259  -7.854818 -2.298363
RightToeBase   0.000000  -2.595023  0.000000

In [36]:
jnt_lst = []
for i in range(21):
    jnt_lst.append(df_buf[0].index[i])
jnt_lst

['Hips_pos',
 'Hips',
 'Spine',
 'Neck',
 'Head',
 'LeftShoulder',
 'LeftArm',
 'LeftForeArm',
 'LeftHand',
 'RightShoulder',
 'RightArm',
 'RightForeArm',
 'RightHand',
 'LeftUpLeg',
 'LeftLeg',
 'LeftFoot',
 'LeftToeBase',
 'RightUpLeg',
 'RightLeg',
 'RightFoot',
 'RightToeBase']

# 3D DTW 연산 위한 array 구성

In [39]:
jnt_lst = [
    'hips_JNT_pos',
    'hips_JNT',
    'spine_JNT',
    'neck_JNT',
    'head_JNT',
    'l_shoulder_JNT',
    'l_arm_JNT',
    'l_forearm_JNT',
    'l_hand_JNT',
    'r_shoulder_JNT',
    'r_arm_JNT',
    'r_forearm_JNT',
    'r_hand_JNT',
    'l_upleg_JNT',
    'l_leg_JNT',
    'l_foot_JNT',
    'l_toebase_JNT',
    'r_upleg_JNT',
    'r_leg_JNT',
    'r_foot_JNT',
    'r_toebase_JNT'
]

# 1. jnt_lst에는 관절 이름이, df_list에는 세 개의 데이터 프레임 존재. 각 데이터 프레임은 관절 개수 * (x, y, z)의 구조
jnt_data = {jnt: [] for jnt in jnt_lst}
# jnt_data_b = {jnt: [] for jnt in jnt_lst}

# 2. 각 관절 이름에 따라 각 데이터 프레임의 x, y, z가 묶여 있고, 프레임 숫자(3)만큼의 길이를 갖는 array 생성
for df in df_list:
    for i, jnt in enumerate(jnt_lst):
        position = df.iloc[i].values
        jnt_data[jnt].append(position)

# for df in df_list_b:
#     for i, jnt in enumerate(jnt_lst):
#         position_b = df.iloc[i].values
#         jnt_data_b[jnt].append(position_b)

# 요구된 형식으로 결과를 저장하는 새로운 딕셔너리 생성
formatted_jnt_data = {}
# formatted_jnt_data_b = {}

# 각 관절에 대해 결과를 요구된 형식으로 변환
for jnt, positions in jnt_data.items():
    formatted_jnt_data[jnt] = np.array(positions)

# for jnt, positions in jnt_data_b.items():
#     formatted_jnt_data_b[jnt] = np.array(positions)
    
# 결과 출력
for jnt, positions in formatted_jnt_data.items():
    print(f"{jnt}:\n{positions}\n")

hips_JNT_pos:
[[-1.25332  89.754211  0.253828]
 [-1.327959 89.904915  0.724199]
 [-1.371685 89.747772  1.14935 ]]

hips_JNT:
[[ 0.271554 -0.06793   1.044649]
 [ 0.270495 -0.634992  1.468915]
 [ 0.226914 -1.292518  1.884882]]

spine_JNT:
[[ 4.671000e-03 -2.702317e+00  9.907600e-02]
 [ 2.558000e-03 -4.080041e+00  3.595700e-02]
 [-6.878000e-03 -5.598317e+00 -7.050800e-02]]

neck_JNT:
[[ 0.06013   1.649928  0.097193]
 [-0.020909  3.852391  0.03719 ]
 [-0.073739  6.81613  -0.060923]]

head_JNT:
[[-1.134144 -0.654619 -0.068749]
 [-1.403814 -0.370355 -0.197857]
 [-1.473313 -0.349851 -0.366863]]

l_shoulder_JNT:
[[-0.592515 -1.744542 -0.073797]
 [-0.690762 -2.080945 -0.213701]
 [-0.527843 -2.890834 -0.383934]]

l_arm_JNT:
[[ 4.619843  1.398346 -0.551397]
 [ 6.573526  0.987751 -0.591955]
 [ 9.500789 -0.148224 -0.618693]]

l_forearm_JNT:
[[ 0.231909  2.70384  -2.213668]
 [-2.005956  3.511819 -2.878868]
 [-5.222422  4.482032 -3.442607]]

l_hand_JNT:
[[-0.062974 -1.342286 -2.686267]
 [-0.143424 -2